### ISSUE TITLE
Define addresses as "constant", this compiles them directly into the bytecode instead of memory/sstore

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/Fantom-FMint#1]
https://github.com/Fantom-foundation/Fantom-FMint/blob/309e7fe1c172e011370902bd94ed9d0d58810977/contracts/FantomCollateral.sol#L80

**Comment by JirkaMalek** [comment]
Internals are now handled as constants. 

We may want to consider using address provider to connect minter to the other contracts in the future versions. That way we can switch service contracts without breaking the core.
