### ISSUE TITLE
Create wFTM first (wrapped FTM, same as wrapped ETH)

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/Fantom-FMint#2]
Trying to cater for both FTM/ERC20 adds a lot of overhead and complexity. Best to use ERC20 standard everywhere.

https://github.com/Fantom-foundation/Fantom-FMint/blob/309e7fe1c172e011370902bd94ed9d0d58810977/contracts/FantomFMint.sol#L100

**Comment by JirkaMalek** [comment]
Wrapped FTM contract is now available in https://github.com/Fantom-foundation/Fantom-wFTM and is already deployed on TestNET 0xf1277d1ed8ad466beddf92ef448a132661956621. We still need to be able to tell, if the token is available for minting through the fMint, so I plan to use TokenRegistry contract to keep that information.
