### ISSUE TITLE
Revert is a hard stop. This can cause downstream systems to fail, instead use conditional statements to fail softly and return error code.

### ISSUE THREAD

**Issue by andrecronje** [Fantom-foundation/Fantom-FMint#3]
https://github.com/Fantom-foundation/Fantom-FMint/blob/309e7fe1c172e011370902bd94ed9d0d58810977/contracts/FantomFMint.sol#L104

**Comment by JirkaMalek** [comment]
I changed the condition checks to return numeric error codes defined in a separate contract source.
